### ISSUE TITLE
"fileURLToPath" is not exported by "__vite-browser-external"

### ISSUE THREAD

**Issue by bennymi** [atomiks/rehype-pretty-code#100]
Hi, I'm currently getting this error on a failed build on Vercel for my SvelteKit app:

```bash
RollupError: "fileURLToPath" is not exported by "__vite-browser-external", imported by 
"node_modules/.pnpm/rehype-pretty-code@0.10.0_shiki@0.14.3/node_modules/rehype-pretty-code/dist/rehype-pretty-code.js".
```

It seems to come from the [test file](https://github.com/atomiks/rehype-pretty-code/blob/024a5b8ec4a56318a6e6eac9221babce031fb851/test/fixtures.test.js#L12).

Is there a way to solve this issue? Maybe excluding test files from the npm package?

**Comment by atomiks** [comment]
This might be fixed in `v0.12.0`, can you check?
