### ISSUE TITLE
Syntax highlighting didn't recognize R language when it's uppercase in backticks

### ISSUE THREAD

**Issue by aster-hu** [atomiks/rehype-pretty-code#114]
**Describe the bug**
When the markdown code block starts with \```R instead of \```r, it didn't recognize the R language and therefore not show the syntax highlighting.

**To Reproduce**

1. Create a markdown file to include R code like this:

\```R
library(dplyr)
mouse.data <- data.frame(
  weight=c(0.9, 1.8, 2.4, 3.5, 3.9, 4.4, 5.1, 5.6, 6.3),
  size=c(1.4, 2.6, 1.0, 3.7, 5.5, 3.2, 3.0, 4.9, 6.3))
\```

2. The code block didn't show syntax highlighting for R lang. As a comparison, the same code starts with \```r shows the syntax highlighting normally.

**Expected behavior**
The code block starting with \```R should show the syntax highlighting for R code

**Desktop (please complete the following information):**
- Device: Mac Mini M2
- OS: Ventura 13.5.2
- Browser Safari

**Comment by atomiks** [comment]
This is a Shiki issue.
