### ISSUE TITLE
Best way to implement file title to the code block ?

### ISSUE THREAD

**Issue by beaussan** [atomiks/rehype-pretty-code#12]
Hi,

First of all, I love the style of this code block rehype plugin !

I was wondering how this plugin can be used to render blocks like this, with the file name / lang icon : 

![image](https://user-images.githubusercontent.com/7281023/150156514-e2da615d-d38d-46a2-a2b1-a4f840142059.png)

What would be the best way to implement it ? Can it be implemented with the current state of the library ?

**Comment by atomiks** [comment]
The code tag receives a `data-language` attribute, so you can add language information to the code that way (using a pseudo-element or such, or a custom MDX component for `code`). 

The file title (`lib/redis.js`) I don't think is possible with meta strings right now, but you could add a component in your MDX that does this itself before your code block, like:

```md
<CodeMeta language="js" filename="lib/redis.js" />

\`\`\`js
// your code
\`\`\`
```


There is a _lot_ more this plugin can be doing to enhance code blocks for sure

**Comment by atomiks** [comment]
Here's how Docusaurus seems to implement it, shouldn't be too hard to add:

https://pbs.twimg.com/media/FJentD_XIAYUhg_?format=jpg&name=large

```md
```js title="..."
```

**Comment by dvlden** [comment]
I'm using `rehype-code-titles` for this specific use-case.
The syntax is pretty straight forward.

```
```ts:lib/mdx.ts
```

**Comment by atomiks** [comment]
@dvlden I'm thinking `title="..."` syntax might be more future proof in compatibility with other features we might want to add. Do you think that syntax is ok?

**Comment by dvlden** [comment]
Definitely! I was just pointing out the package I'm using to solve this.
I do like `title` _attribute like_ much better. 👍 

Does make sense for future options too.
