### ISSUE TITLE
`rehype-pretty-code` doesn't preserve the language if it's unknown

### ISSUE THREAD

**Issue by jackyzha0** [atomiks/rehype-pretty-code#136]
Before upgrading to `0.12.1`, Quartz used to have code that looks like this:

```ts
visit(tree, "code", (node: Code) => {
  if (node.lang === "mermaid") {
    node.data = {
      hProperties: {
        className: ["mermaid"],
      },
    }
  }
})
```

This would run in a `remark` plugin _before_ `rehype-pretty-code` does. I'm guessing that the old implementation would respect the `hProperties` on the `code` block but `shikiji` straight up just replaces it? In any case, this would also be solved if `data-language` contained the code block language even if it isn't a recognized language (right now, it seems to default to the empty string if it's not detected)

**Comment by jackyzha0** [comment]
Related issue within Quartz: https://github.com/jackyzha0/quartz/issues/638

**Comment by jackyzha0** [comment]
workaround based off of the `lang` parsing here: https://github.com/atomiks/rehype-pretty-code/blob/master/src/utils.ts#L53

```ts
visit(tree, "code", (node: Code) => {
  if (node.lang === "mermaid") {
    node.data = {
      hProperties: {
        className: ["language-mermaid"], // use language- prefix
      },
    }
  }
})
```

**Comment by atomiks** [comment]
@jackyzha0 I think the issue was the transformation of `properties` wasn't respecting the existing properties, can you check if the linked PR ^ fixes it?
