### ISSUE TITLE
Add an option that would show line numbers

### ISSUE THREAD

**Issue by dvlden** [atomiks/rehype-pretty-code#14]
Would be great if it had an option that would add a `class` or `data-*` attribute to the code block.

The following package has such option, but I'm not sure if your package has it as well, but it's undocumented?
[rehype-prism-plus](https://www.npmjs.com/package/rehype-prism-plus)

In short, this is their syntax
```
```js {1,3-4} showLineNumbers
```

I added the styles with `counter`, but I don't want to have such style everywhere, especially not on single line blocks.

---

BTW – Great package, I am just developing new personal portfolio/blog and I found this some time ago through Twitter. Keep it up!

**Comment by atomiks** [comment]
Yeah this package doesn't have that. Would be good to add for sure. Something just like, `data-line-numbers` on the `<code>` tag?

**Comment by dvlden** [comment]
Yes. Something as simple as this, would be amazing!
