### ISSUE TITLE
`fs.readFileSync()` expects a string

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [atomiks/rehype-pretty-code#148]
In this snippet from the homepage, when I tried using it as is for a custom theme on my [blog](https://meje.dev/blog), in `getStaticProps`, Next.js throws an error as shown in this issue title. 

https://github.com/atomiks/rehype-pretty-code/blob/1c627dc05802ca4c4cce49150e6ce2f0d9fdc2c8/website/src/app/index.mdx#L243-L246

But, when I passed the file path as a string to my custom theme, the error was gone. Maybe this needs revision? If yes, I'd love to make the necessary changes and send a PR.

**Comment by kaf-lamed-beyt** [comment]
Oh! Okay then. 

Should I submit a PR that addresses it?

**Comment by atomiks** [comment]
Sure
