### ISSUE TITLE
Highlight Lines doesn't work

### ISSUE THREAD

**Issue by chaveamin** [atomiks/rehype-pretty-code#152]
I'm using Nextjs 14 and MDX for blog posts. used `{1-3,4}` to highlight some lines. It does add the attributes but doesn't add the css for colors
![Screenshot 2024-01-07 105551](https://github.com/atomiks/rehype-pretty-code/assets/78597787/2c4d151b-7935-4f48-bcbb-6afa9f0e19b3)
![Screenshot 2024-01-07 111551](https://github.com/atomiks/rehype-pretty-code/assets/78597787/bfd90e63-3eb4-4d99-b341-befb80fb7865)

**Comment by atomiks** [comment]
There is no CSS as it's an unstyled library that provides logic, you add it yourself.

**Comment by atomiks** [comment]
Added some docs, hopefully it's clearer: [docs: add ToC and Styles sections](https://github.com/atomiks/rehype-pretty-code/commit/e559125a44d8b33d0307d965f900f3601ae4f72b)
