### ISSUE TITLE
Types are no lonnger exported from the NPM package

### ISSUE THREAD

**Issue by mwskwong** [atomiks/rehype-pretty-code#160]
After installing the latest version, observe the content of `dist/index.d.ts`. The only export is `rehypePrettyCode()` all the types are still present but are no longer exported.

**Comment by mburumaxwell** [comment]
Seen the same behaviour in version `0.12.4`. Relates to the move to tsup/esbuild.
Adding `export * from './types` to `src/index.ts` should solve this.
@atomiks are you accepting PRs for this?

**Comment by atomiks** [comment]
Sorry! Yes @mburumaxwell feel free
