### ISSUE TITLE
Problems compiling using Next JS 12

### ISSUE THREAD

**Issue by carlos-burelo** [atomiks/rehype-pretty-code#21]
Hello, I have found a small inconvenience when compiling a project in NextJS, apparently it cannot import shiki by default, but when I review the file I see that it is well exported
I attach a screenshot of the error in question and the version that I am using in the project

![image](https://user-images.githubusercontent.com/56522783/153108332-0a4e0289-d264-4a38-bafd-ef656aadd989.png)

**Comment by atomiks** [comment]
It doesn't look like Shiki even has a default export so I'm confused how it was working for me to begin with 😅

**Comment by carlos-burelo** [comment]
Well, unlike how you apply it in the documentation, I use it as a plugin for `next-mdx-remote`, I don't know if using it this way has the effect of not being able to use the given export, I understand that `next-mdx-remote` is also an ESM module

![image](https://user-images.githubusercontent.com/56522783/153112758-1661bcbd-eedb-4670-a808-dccdfbb38942.png)

**Comment by atomiks** [comment]
Will fix this in a sec by importing the modules directly rather than the whole `shiki` package

**Comment by atomiks** [comment]
Should be fixed in `v0.2.2`
