### ISSUE TITLE
TypeError: nodesToWrap.at is not a function at wordHighlighter

### ISSUE THREAD

**Issue by HamedBahram** [atomiks/rehype-pretty-code#22]
# word highlighter works on local machine but seems to be throwing an error when deploying to Vercel

Here are the options I'm using:

const prettyCodeOptions = {
  theme: 'material-palenight',
  onVisitLine(node) {
    if (node.children.length === 0) {
      node.children = [{ type: 'text', value: ' ' }]
    }
  },
  onVisitHighlightedLine(node) {
    node.properties.className.push('highlighted')
  },
  onVisitHighlightedWord(node) {
    node.properties.className = ['highlighted', 'word']
  }
}

the markdown file I'm trying to highlight contains the following code fence block

```jsx {2} showLineNumbers /name="alice"/ title="home.jsx"
import Link from 'next/link'
import Example from './example.mdx'

const Home = () => {
  return <Example name="alice" />
}

export default Home
```

Thank you

**Comment by atomiks** [comment]
Hmm `.at()` is a new method so maybe the Vercel runtime doesn't support it. We can either change this method or you could add a polyfill

**Comment by HamedBahram** [comment]
Thank you James for your prompt response and for making the change.

Cheers,
*Hamed*
