### ISSUE TITLE
Caching highlighters requires restarting the app after changing the theme

### ISSUE THREAD

**Issue by silvenon** [atomiks/rehype-pretty-code#26]
Hey James! 👋 

In my Remix app I noticed that changing the theme only takes after restarting the server (try changing the theme in [this repro](https://github.com/silvenon/repro/tree/remix-mdx-bundler-cache)). First I thought that the problem was in Remix itself, then somewhere in mdx-bundler, perhaps esbuild, but eventually I figured out that it's (probably) because of the way `highlighterCache` works.

https://github.com/atomiks/rehype-pretty-code/blob/d64e67bf4f2865066a61f0408f0c69bf81b68fb9/src/index.js#L73-L75

It's true that in my case this is a development-only problem, but one case where this is a bigger problem is if you wanted to compile Markdown twice using different pairs of `light` and `dark` themes, I think that currently isn't possible because the highlighters are cached using those keys.

I'm not sure how to solve this problem, maybe use the hash of the theme object as the key?

**Comment by silvenon** [comment]
Also, what was the reason for caching the highlighters at all? Without it they would only be created once per processor anyway, no?

**Comment by atomiks** [comment]
Without caching, it'd need to await the highlighter for every single code block on a page

**Comment by silvenon** [comment]
It would be created once per _tree_, not each code block in the tree, see my PR.
