### ISSUE TITLE
Replace with real Fragment

### ISSUE THREAD

**Issue by kylebutts** [atomiks/rehype-pretty-code#28]
https://github.com/atomiks/rehype-pretty-code/blob/c8a99fdd91ea9c1171399cf2341d8e68de6852e7/src/index.js#L10

Hi there, I'm super excited about this for my new site. I am trying to not wrap my outputted code in the `<div data-rehype-pretty-code-fragment=""></div>` tag. I see in the code that this should be possible, but I'm not sure how to. Any help would be appreciated

**Comment by atomiks** [comment]
In the MDX components provider, something like this should work:

```js
const mdxComponents = {
  div(props) {
    if (props['data-rehype-pretty-code-fragment'] != null) {
      return props.children;
    }
    return <div {...props} />;
  }
};
```

**Comment by kylebutts** [comment]
Ahh, that makes perfect sense. Thank you!
