### ISSUE TITLE
Support highlighting words across syntax boundaries

### ISSUE THREAD

**Issue by atomiks** [atomiks/rehype-pretty-code#3]
Because the `<span>` tags break up words by syntax boundaries, we can't highlight text like `theme: 'x'` in a code block, only `theme`, or `x`, without any punctuation.

https://github.com/atomiks/mdx-pretty-code/blob/61727cfd15abbd190d596735e3f6515352ff52e6/src/index.js#L110-L118

I experimented with removing the `<span>` tags, `.textContent`, etc, but didn't come up with a viable solution.

cc: @renrizzolo maybe you have some ideas?

**Comment by renrizzolo** [comment]
I've been playing around with this. 
I have something that works across/within all boundaries (as far as I can tell). 
Although there is most likely some weird edge cases I haven't found yet.

It gets a bit tricky when dealing with partial repetition (having to look ahead).

I had another thought, you could add a way to highlight different words per line. But I'm not sure what you would use for a delimiter, given the word itself could contain _any_ character.

e.g `/carrot|tomato/` split on the pipe.

**Comment by atomiks** [comment]
@renrizzolo currently refactoring to a Rehype plugin and we can check the cumulative value of each span node in the AST to find all the text across a boundary, I think

**Comment by atomiks** [comment]
Fixed in `v0.2.0` thanks to @renrizzolo's amazing work
