### ISSUE TITLE
 Shiki could be integrated into the rehype-pretty-code package?

### ISSUE THREAD

**Issue by carlos-burelo** [atomiks/rehype-pretty-code#30]
![image](https://user-images.githubusercontent.com/56522783/161396838-4d3b6ead-00c1-4bcc-9afd-3516e04a47e1.png)
I have been using the library in these weeks and I have been fascinated with everything it can do.
Lately I've had a problem using it in production with next-mdx-remote, it seems to be the platform I use, it can't find shiki in production.

I am attaching some screenshots of how I am implementing the rendering in production using the vercel ISR to generate and update the pages.

![image](https://user-images.githubusercontent.com/56522783/161397227-d4308788-ff23-47dc-9f98-483d38c8eba6.png)

![image](https://user-images.githubusercontent.com/56522783/161397269-74d6a317-f814-4807-900b-00f89b457c0b.png)

![image](https://user-images.githubusercontent.com/56522783/161397390-8c1cccb9-48ea-4072-b9b9-35dfc4b4f422.png)

**Comment by atomiks** [comment]
Shiki is in v0 so it's better to make it a peer dep to allow upgrading easily. Also you might want to use Shiki elsewhere without relying on `rehype-pretty-code`. I'm not sure why you're getting that issue but I've also had random problems with Netlify regarding deps, not sure if I've had this Shiki one in particular

**Comment by thien-do** [comment]
Next.js requires some trick to use Shiki, because Shiki loads file in a way that Next.js doesn't know and thus doesn't bundle the necessary themes and languages (this is oversimplified).

See this for a working example on how to have Shiki working: https://github.com/thien-do/memos.pub/blob/06a2abdfea37a2ce127673c45403441388650c34/lib/mdx/compile/highlight.ts#L17-L24

**Comment by atomiks** [comment]
@thien-do this repo's website uses Next.js and didn't require that, although it's hosted on Netlify not Vercel

**Comment by carlos-burelo** [comment]
@thien-do
It seems that I have found a solution to the problem, I came up with the idea of ​​moving the shiki assets to the /public folder of nextjs and creating a condition to use different directories depending on the execution environment of nextjs, and apparently this request was the that ended my 2 weeks of torment with shiki

![image](https://user-images.githubusercontent.com/56522783/162770569-8ce4ea9e-3192-487c-9f59-b8ec599a8f5c.png)

Regarding the variable SHIKI_PRODUCTION_PATH I just put a random value so that this is the indicator in production to take the other directory instead of using the development directory

![image](https://user-images.githubusercontent.com/56522783/162772107-c8922bf1-e9eb-48e6-88e5-adcfa4d606d3.png)

In the end the method I use gave me the basis to implement mine, so I give my sincere thanks, I tried to implement the same method of passing the assets to the lib folder, but that gave me the same error as before, but with a different path so I chose to pass them to the /public folder as this is kept intact in production.

![image](https://user-images.githubusercontent.com/56522783/162771293-c6214182-2461-4bc3-88b1-eb7e8dd022cd.png)

I deeply thank both of you for helping me solve this problem that had been unsolved for several days (and many unnecessary deployments to production 😆)

**Comment by thien-do** [comment]
haha good to hear @carlos-burelo , I wasted like 20 deployments to test that back then

@atomiks yeah I think it's more on Vercel than Next.js. I read some where that Vercel deletes the Shiki files after compiled because Vercel thinks they are not needed (not imported per-se)
