### ISSUE TITLE
Add the data-theme key to the wrapping pre element 

### ISSUE THREAD

**Issue by beaussan** [atomiks/rehype-pretty-code#31]
# Problem

When styling with a custom theme (for example, light and dark theme), the data theme only applies to the `code` element, and not the wrapping `pre`. This makes it a bit harder to style properly since you can't style the `pre` element at all, since you can't change the style depending on the children's data keys.

![image](https://user-images.githubusercontent.com/7281023/161401899-18c6c7d6-b6b2-4522-bde7-91b56f641332.png)

# Possible workaround

Using a custom renderer for the `pre` element in react to look at the children's value

# Possible solution

Add the `data-theme` to the `pre` element

Pr : #32 , if any contributors think it's not a good idea, feel free to tell me so, I will delete the pr ! =)

**Comment by atomiks** [comment]
I've personally only ever styled the `<code>` block, the `<pre>` element was just for whitespace. Is that not possible in your styling situation?

**Comment by beaussan** [comment]
The default typography plugin of tailwind adds the whitespace on the pre element, I could change it a lot but I guess I'm not the only one that used the tailwind typography plugin with markdown

**Comment by beaussan** [comment]
See the playground example : https://play.tailwindcss.com/av7tPFOfwg

Yes, I could modify the typography tailwind's config to modify the spacing to be in the `<code>` rather than the `<pre>` block, but having the theme on the pre block makes it easier to deal with; and again, if you don't think it's a good idea, we can close it and same with the pr !

**Comment by atomiks** [comment]
I guess it's fine, IIRC Prism also does this, but we'd need to add the `data-language` too probably.

**Comment by beaussan** [comment]
I added the `data-language` to the `<pre>` element in the pr accordingly

**Comment by thien-do** [comment]
I think @beaussan 's idea makes sense. It's hard to say whether spacing and background for a block of code should be done in `pre` or in `pre > code`. The number of tools that choose the former (like Tailwind Typography) is quite large to ignore. So i think it's good to add :D

**Comment by thien-do** [comment]
Also side note is that we won't need this if we have `:has` :( https://css-tricks.com/the-css-has-selector/

**Comment by atomiks** [comment]
Sorry I forgot about this 😄 I think it does cause a breaking change which is why I didn't merge already, although bumping it to `v0.3` should be fine.
