### ISSUE TITLE
Performance degradation between `0.2.4` and `0.2.5`: heap out of memory.

### ISSUE THREAD

**Issue by brillout** [atomiks/rehype-pretty-code#36]
It seems that https://github.com/atomiks/rehype-pretty-code/commit/8885e75ce9491986d6cb2aed1fd3d1e39e6e5309 has drastic performance degradation on memory usage.

Reproduction: https://github.com/brillout/rehype-pretty-code_performance-degradation-reproduction.

(Btw. thanks for `rehype-pretty-code`, FYI I'm using it for https://vite-plugin-ssr.com/ and https://telefunc.com/ and I really like the code blocks :-).)

**Comment by atomiks** [comment]
cc @silvenon

**Comment by silvenon** [comment]
Should work after the fix in the PR, I tried it. 👍

**Comment by brillout** [comment]
I can confirm it works again. Thanks!
