### ISSUE TITLE
Highlight Words

### ISSUE THREAD

**Issue by dvlden** [atomiks/rehype-pretty-code#39]
I tried to highlight multiple words like this:

```
```sh /"Nenad Novakovic"|"dvlden@users.noreply.github.com"/
```

And also like this:

```
```sh /"Nenad Novakovic"/ /"dvlden@users.noreply.github.com"/
```

But neither approach has worked. In the docs, I saw an example with a single word only. Is this not a possibility yet and may I know if the regex going to be an option?

Good day!

**Comment by atomiks** [comment]
This is now possible in `v0.4.0` thanks to @ttwrpz:

````
```js /word/ /otherword/
````
