### ISSUE TITLE
Supported languages

### ISSUE THREAD

**Issue by jjangga0214** [atomiks/rehype-pretty-code#40]
Hi!

May I ask for the list of supported languages?

Thanks for this awesome project!

**Comment by atomiks** [comment]
It's Shiki's default ones. I think you can load more custom ones as well though, it's documented on the docs website

**Comment by jjangga0214** [comment]
Oh, Thanks. 
I found the list from https://github.com/shikijs/shiki/blob/main/docs/languages.md
