### ISSUE TITLE
Regular Expression `/(?<!\/.*?)showLineNumbers/` doesn't work on Safari

### ISSUE THREAD

**Issue by mashirozx** [atomiks/rehype-pretty-code#48]
https://github.com/atomiks/rehype-pretty-code/blob/b96a0caec5e85b9b30632042287a1da30b0849a5/src/index.js#L204-L210

Works on Chrome, but on Safari:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/16148054/203800695-f062a0be-e6e0-4108-90dd-02fd971c33f3.png">

![Can I use](https://user-images.githubusercontent.com/16148054/203800224-85088db4-1eab-4ae0-9278-e57d56c95e5b.png)
[ref](https://caniuse.com/js-regexp-lookbehind)

**Comment by atomiks** [comment]
cc @ttwrpz, can we use an alternative regex here?

**Comment by mashirozx** [comment]
FYI: maybe this will help: https://stackoverflow.com/a/11347100/8083009

**Comment by atomiks** [comment]
Maybe this `(?!.*\/).*showLineNumbers(?:\{(\d+)})?`

**Comment by ttwrpz** [comment]
I'll trying to fix this by tmr (GMT+7). Sorry!

**Comment by mashirozx** [comment]
Fixed in  #49 
<img width="521" alt="image" src="https://user-images.githubusercontent.com/16148054/203823236-076e89a9-f5dc-493a-b9eb-066354a36b01.png">
