### ISSUE TITLE
An unexpected highlighted word that matches in filename in v0.6.0

### ISSUE THREAD

**Issue by B2o5T** [atomiks/rehype-pretty-code#52]
````
```js filename="a/hello/file.js"
console.log("hello")
```
````
<img width="615" alt="image" src="https://user-images.githubusercontent.com/7361780/209472970-29eb12ca-6ec8-40e9-b9b8-e545bf83bcdf.png">
<img width="393" alt="image" src="https://user-images.githubusercontent.com/7361780/209472983-03580d16-a95f-479a-b69e-6b6b8bdb345d.png">

originally reported in https://github.com/shuding/nextra/issues/1088

**Comment by atomiks** [comment]
What is `filename` from? The check internally uses `title` to filter it out so maybe that's why:

https://github.com/atomiks/rehype-pretty-code/blob/8d6f00dcb2bd5abf17549879eef2f5748b69587b/src/index.js#L170-L173

**Comment by B2o5T** [comment]
`filename` is our custom metadata prop that will be rendered as header for code block
