### ISSUE TITLE
Is compatibility with NextJS 13 contemplated?

### ISSUE THREAD

**Issue by carlos-burelo** [atomiks/rehype-pretty-code#55]
Hello again :)

I recently tried to migrate a project to nextjs 13 that I had using their library and as I had contemplated, I assumed that this version would break with compatibility.

Apparently, it seems that the vscode-onigurama WebAssembly file could not be opened.

![image](https://user-images.githubusercontent.com/56522783/211112404-2fd85ce5-a69f-4cab-bdfb-4bc69450cd5b.png)

For a little more context, this is my package.json

![image](https://user-images.githubusercontent.com/56522783/211114082-972b146e-cfad-453b-b761-7c1803ffa4a2.png)

**Comment by atomiks** [comment]
Seems like an error unrelated to this library. One of my sites is on Next.js 13 and it works with `v0.6.0`, although it's not using the `/app` directory.

**Comment by atomiks** [comment]
There's an issue filed for Next.js and Shiki: 

- https://github.com/shikijs/shiki/issues/398
- https://github.com/vercel/next.js/issues/44316

**Comment by carlos-burelo** [comment]
So is it more of a WebAssembly incompatibility in the React Server Components than a library error as such? This will take a long time until shiki is updated ._.

**Comment by atomiks** [comment]
Does making it a client component work for now? `'use client';`

**Comment by carlos-burelo** [comment]
Not for now, since the `serialize` method must occur in a `page` because it is the one that has to be executed on the server, but it is assumed that if it is a React Server Component, by default it must have access to the APIs of the server

**Comment by selenecodes** [comment]
> There's an issue filed for Next.js and Shiki:
> 
> * [Can't load shiki vscode-oniguruma in Next 13 react server component shikijs/shiki#398](https://github.com/shikijs/shiki/issues/398)
> * [Next 13 Shiki vscode-oniguruma wasm file not found in React Server Component vercel/next.js#44316](https://github.com/vercel/next.js/issues/44316)

A workaround has been posted on: https://github.com/shikijs/shiki/issues/398, simply add this to your `next.config.js`. All credits go to https://github.com/ISnackable
```js
experimental: {
    // ...
    serverComponentsExternalPackages: [
      'vscode-oniguruma',
      'shiki',
    ],
  },
  ```

**Comment by selenecodes** [comment]
> There's an issue filed for Next.js and Shiki:
> 
> * [Can't load shiki vscode-oniguruma in Next 13 react server component shikijs/shiki#398](https://github.com/shikijs/shiki/issues/398)
> * [Next 13 Shiki vscode-oniguruma wasm file not found in React Server Component vercel/next.js#44316](https://github.com/vercel/next.js/issues/44316)

A workaround has been posted in https://github.com/shikijs/shiki/issues/398
