### ISSUE TITLE
Word highlighting range does not work when multiple words are on one line

### ISSUE THREAD

**Issue by atomiks** [atomiks/rehype-pretty-code#57]
Right now the `wordHighlighter` range works _per line_, not per occurrence of words. So this fails to highlight the occurrences of words correctly:

````
```js /word/1,2
const word = 'word'; // word
const word2 = 'word'; // word
```
````

Only the `word` const and the `word` string on the first line should be highlighted, but it highlights every occurrence of `word` on the first and second lines.

I think this function needs to take an argument:

https://github.com/atomiks/rehype-pretty-code/blob/0c14334d1a92b00ee6f09006062ef196787e260e/src/word-highlighter/wordHighlighter.js#L32

cc: @renrizzolo

**Comment by renrizzolo** [comment]
From memory, the numbers represent the lines, not the occurrences. This might have been a misunderstanding on my part. 
It checks out in the fixtures, just the line number one doesn't have duplicated words in them to make it obvious.

**Comment by atomiks** [comment]
Yeah it was intended to be per occurrence/instance of the word, irrespective of the line. This makes it more granular and configurable, while the line method is more limiting (although could be useful in certain cases, seems less so)

<img width="830" alt="Screenshot 2023-01-09 at 9 34 34 pm" src="https://user-images.githubusercontent.com/22450188/211288752-9f9274e1-38d6-4c6a-87f1-c1939d3397b0.png">

**Comment by renrizzolo** [comment]
Oh do you mean to ignore lines all together for word highlighting?

so 
```/carrot/2,3
carrot carrot
carrot
```
becomes 
carrot `carrot`
`carrot`

(as opposed to resetting the count each line)

**Comment by atomiks** [comment]
Yep exactly
