### ISSUE TITLE
Doesn't seem to work with xdm (MDX 2)

### ISSUE THREAD

**Issue by silvenon** [atomiks/rehype-pretty-code#6]
I tried this plugin with xdm:

```js
import fs from 'node:fs/promises'
import { compile } from 'xdm'
import { createRemarkPlugin } from '@atomiks/mdx-pretty-code'

const prettyCode = createRemarkPlugin({
  shikiOptions: {
    theme: JSON.parse(
      await fs.readFile('node_modules/shiki/themes/github-light.json', 'utf8')
    )
  }
})

const mdxContent = `
# Hello World

~~~js
console.log('Hello World')
~~~
`.trim()

const result = await compile(mdxContent, {
  remarkPlugins: [prettyCode],
})

console.log(String(result))
```

But I'm getting the following error:

```
Error: Cannot handle unknown node `raw`
    at Object.unknown (file:///Users/silvenon/Code/test/node_modules/hast-util-to-estree/index.js:155:9)
    at Object.one [as handle] (file:///Users/silvenon/Code/test/node_modules/zwitch/index.js:52:17)
    at all (file:///Users/silvenon/Code/test/node_modules/hast-util-to-estree/index.js:583:28)
    at Object.root (file:///Users/silvenon/Code/test/node_modules/hast-util-to-estree/index.js:508:20)
    at Object.one [as handle] (file:///Users/silvenon/Code/test/node_modules/zwitch/index.js:52:17)
    at toEstree (file:///Users/silvenon/Code/test/node_modules/hast-util-to-estree/index.js:119:24)
    at file:///Users/silvenon/Code/test/node_modules/xdm/lib/plugin/rehype-recma.js:15:20
    at wrapped (file:///Users/silvenon/Code/test/node_modules/trough/index.js:111:16)
    at next (file:///Users/silvenon/Code/test/node_modules/trough/index.js:62:23)
    at done (file:///Users/silvenon/Code/test/node_modules/trough/index.js:145:7)
```

I tried the same with `@mdx-js/mdx` and it works as expected. Maybe it's an incompatibility with micromark?

**Comment by atomiks** [comment]
Seems to be due to adding HTML to the tree? Does adding something like https://github.com/remarkjs/remark-html work?

**Comment by silvenon** [comment]
Yeah, remark-html didn't work, but I played around trying to convert that `html` node into `mdxJsxFlowElement`, the way that xdm's `remark-mdx` does:

```js
import fs from 'node:fs/promises'
import { compile } from 'xdm'
import { remarkMdx } from 'xdm/lib/plugin/remark-mdx.js'
import { remarkMarkAndUnravel } from 'xdm/lib/plugin/remark-mark-and-unravel.js'
import { createRemarkPlugin } from '@atomiks/mdx-pretty-code'
import { visit } from 'unist-util-visit'
import { unified } from 'unified'
import remarkParse from 'remark-parse'

const toMdx = unified().use(remarkParse).use(remarkMdx).use(remarkMarkAndUnravel).parse

const prettyCode = createRemarkPlugin({
  shikiOptions: {
    theme: JSON.parse(
      await fs.readFile('node_modules/shiki/themes/github-light.json', 'utf8')
    )
  }
})

const mdxContent = `
# Hello World

~~~js
console.log('Hello World')
~~~
`.trim()

const result = await compile(mdxContent, {
  remarkPlugins: [prettyCode, () => (tree) => {
    visit(tree, (node, index, parent) => {
      if (node.type === 'html') {
        parent.children[index] = toMdx(node.value).children[0].children[0]
      }
    })
  }],
})

console.log(String(result))
```

Not sure if there's a simpler way.

**Comment by silvenon** [comment]
But remark plugins should be allowed to create `html` nodes, so this is probably an xdm question, not specific to this plugin.

**Comment by silvenon** [comment]
Btw, I tried rehype-raw as well, unfortunately it fails when coming across `mdxJsxFlowElement` nodes.

**Comment by silvenon** [comment]
Just to post back the solution, you were right, I had to use rehype-raw 😄  I just had to set the `passThrough` options for MDX-specific nodes:

```js
await compile(mdxContent, {
  remarkPlugins: [prettyCode],
  rehypePlugins: [[rehypeRaw, { passThrough: ['mdxJsxFlowElement', 'mdxjsEsm'] }]]
})
```

**Comment by atomiks** [comment]
Would be great to add this to the docs! What are you using XDM for here?

**Comment by wooorm** [comment]
Plugins that (hope to / exclusively) work with MDX should not inject `html` nodes! MDX replaces HTML with JSX, so HTML doesn’t really make sense (although it used to be buggy but possible)

See:
- https://github.com/mdx-js/mdx/issues/1330#issuecomment-726628345
- https://github.com/mdx-js/mdx/issues/1820#issuecomment-970430877

**Comment by atomiks** [comment]
@wooorm given that Shiki returns an HTML string what do you suggest we do? How to convert it into an AST?

**Comment by wooorm** [comment]
Create an AST: something like what https://github.com/sachinraja/shiki-renderer-hast or https://github.com/rsclarke/rehype-shiki/blob/master/index.js does probably.
(I searched for https://github.com/search?q=shiki+rehype and https://github.com/search?q=shiki+hast)

**Comment by atomiks** [comment]
I don't have experience in this area, how do I "use" the tree from `shiki-renderer-hast`? Before, setting `node.html` and `node.value` rendered it out. Setting `node.value = tree` stringifies it. I saw `rehype-shiki` does `node.children` but that doesn't seem to have an effect.

**Comment by wooorm** [comment]
remark (mdast) is for markdown, rehype (hast) is for HTML. Some more information on why that is, can be found here: https://github.com/remarkjs/remark-rehype#what-is-this.

This package exports something called “remark”, but it has more to do with HTML, so rehype would be more apt.
But there is a way to “embed” hast into remark: the first link I shared before (“MDX v2 node.type="html"”) goes to a comment that explains how to do that

**Comment by atomiks** [comment]
Thanks for pointing me in the right direction! I'm currently refactoring the package to be a Rehype plugin and I'll keep this issue open until it's complete

**Comment by wooorm** [comment]
Do ping if you have further Qs!

**Comment by silvenon** [comment]
Thanks to both of you for expanding on this topic!

> Would be great to add this to the docs! What are you using XDM for here?

Just to answer your question, I'm using xdm through [mdx-bundler](https://github.com/kentcdodds/mdx-bundler). 😃

**Comment by atomiks** [comment]
Refactored to a new package called `rehype-pretty-code` 🎉 

Also has a site now: https://rehype-pretty-code.netlify.app/

**Comment by silvenon** [comment]
Sweet! 😍 😍 😍
