### ISSUE TITLE
Expose filtered meta props

### ISSUE THREAD

**Issue by khinshankhan** [atomiks/rehype-pretty-code#60]
For the new feature, filter meta string, it'd be neat to have these props available in the pre block. My own usecase is that I'd like more control over the title block when replacing the pre block, eg:
```tsx
  pre: (props) => {
    const ref = useRef<HTMLElement>(null);
    // able to poke around props to get language, theme, and custom 'filename'
    return <>
      <div>{filename} {morestuff}</div>
      <pre>
        {cloneElement(props.children as ReactElement, { ref })}
      </pre>
    </>
  }
```

A thought: since they'll be key value pairs, they could potentially become data attributes eg `data-${key}="${value}"`? Not sure.

**Comment by atomiks** [comment]
The filter meta string feature is only to prevent conflicts of the library with other ones, it doesn't really provide any features. The title block is a `div`, so you'd check for `rehype-pretty-code-title` in the `div` component to customize the rendering of it

**Comment by IanMitchell** [comment]
I've found myself wanting greater control over the title display as well, in order to colocate information about the codeblock's language. Would an `onVisitTitle` option work for you @khinshankhan? I think that would be enough for me - happy to take a look at PRing a change if atomiks thinks that's a good solution too

**Comment by atomiks** [comment]
@khinshankhan  I think you want this new plugin: https://github.com/remcohaszing/rehype-mdx-code-props

@IanMitchell that seems fine to me. I'm going to add `onVisitTitle` and `onVisitCaption` hooks in #93.

**Comment by atomiks** [comment]
New visitor hooks are in `v0.10.0`, let me know if anything else is needed
