### ISSUE TITLE
How do I use this with sandpack?

### ISSUE THREAD

**Issue by colinsteidtmann** [atomiks/rehype-pretty-code#66]
I want to wrap some mdx code blocks with Sanpack components, like how [react.org does it](https://github.com/reactjs/reactjs.org/blob/38bf76a4a7bec6072d086ce8efdeef9ebb7af227/beta/src/content/learn/adding-interactivity.md?plain=1#L29):

```
<Sandpack>

``js
function playWithThisInteractiveExample() {...}
``
</Sandpack>

```

**Comment by atomiks** [comment]
I don't know, but it would be great to allow for easy Sandpack integration to make the code blocks editable!
