### ISSUE TITLE
Add `translate='no'` to code blocks

### ISSUE THREAD

**Issue by jahirfiquitiva** [atomiks/rehype-pretty-code#74]
That way, readers can translate your content into their own language, without it messing up code snippets

Context:
https://twitter.com/joshwcomeau/status/1646275569657470978

**Comment by atomiks** [comment]
As the tweet mentions, this is only necessary if you use `<pre>` without `<code>`; Markdown parsers and this library generate:

```html
<pre>
  <code>
    ...
  </code>
</pre>
```

Therefore it's not necessary.
