### ISSUE TITLE
All options in type declaration are marked as required which doesn't appear to line up with the code itself

### ISSUE THREAD

**Issue by jenewland1999** [atomiks/rehype-pretty-code#76]
The types provided for the options object say that all items are required, yet the documentation and source code suggest that not all the options are required.

https://github.com/atomiks/rehype-pretty-code/blob/445a50ef8633594a5c9af792b77041f6b058695b/index.d.ts#L5-L15

**Comment by atomiks** [comment]
I'm not sure what the common convention is here, but an `Options` object lists all the properties which can be passed, but functions that accept it would themselves specify `Partial<Options>`.

**Comment by jenewland1999** [comment]
So, the case I particularly had was defining an object literal and wanting to use the `satisfies` keyword to check it against the valid options. But if I omit the required fields (all of them in this case) TS complains at me. However, if I use Partial, then it won't complain at all even if I don't include any options. Which I guess is fine if it provides fallbacks for all the options when not specified.

**Comment by atomiks** [comment]
yes, I guess `satisfies Partial<Options>` is fine
