### ISSUE TITLE
not work with nextjs13.4

### ISSUE THREAD

**Issue by langliu** [atomiks/rehype-pretty-code#78]
for example https://codesandbox.io/p/sandbox/vigilant-payne-u63k77

**Comment by atomiks** [comment]
I guess I need to update the docs for how to use it in the `/app` dir.

Here's some info: https://github.com/atomiks/rehype-pretty-code/issues/55#issuecomment-1384228217

**Comment by atomiks** [comment]
Testing this locally, make sure you **aren't** using the Rust option:

```diff
const nextConfig = {
  experimental: {
-  mdxRs: true,
+  mdxRs: false,
  },
};
```

**Comment by atomiks** [comment]
Added to the docs.
