### ISSUE TITLE
How to use it with `unified` manually?

### ISSUE THREAD

**Issue by baurine** [atomiks/rehype-pretty-code#84]
In the doc, it only mentions how to use it with `@next/mdx`, but if I don't use `@next/mdx`, how should I do?

The following code is how I use it:

```typescript
import { Octokit } from "octokit"
import rehypeAutolinkHeadings from "rehype-autolink-headings"
import rehypePrettyCode from "rehype-pretty-code"
import rehypeSlug from "rehype-slug"
import rehypeStringify from "rehype-stringify"
import remarkGfm from "remark-gfm"
import remarkParse from "remark-parse"
import remarkRehype from "remark-rehype"
import { unified } from "unified"

const token = process.env.GITHUB_API_TOKEN ?? ""
const org = process.env.GITHUB_TARGET_ORG ?? ""
const repo = process.env.GITHUB_TARGET_REPO ?? ""

const sdk = new Octokit({ auth: token })

export async function getIssue(slug: string) {
  const res = await sdk.rest.issues.get({
    owner: org,
    repo,
    issue_number: Number(slug),
  })

  const processedContent = await unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype)
    .use(rehypeSlug)
    .use(rehypeAutolinkHeadings)
    .use(rehypePrettyCode, { theme: "one-dark-pro" })
    .use(rehypeStringify)
    .process(res.data.body ?? "")
  const htmlContent = String(processedContent)

  return {
    ...res.data,
    htmlContent,
  }
}
```

When I build it, it reports the following error:

```shell
./src/lib/github-issues.ts:42:10
Type error: Argument of type 'Plugin<[(Options | undefined)?] | void[], Root, string>' is not assignable to parameter of type 'Preset | PluggableList'.

  40 |     .use(rehypeAutolinkHeadings)
  41 |     .use(rehypePrettyCode, { theme: "one-dark-pro" })
> 42 |     .use(rehypeStringify)
     |          ^
  43 |     .process(res.data.body ?? "")
  44 |   const htmlContent = String(processedContent)
  45 | 
 ELIFECYCLE  Command failed with exit code 1.
```

VS Code also report the same error:

![image](https://github.com/atomiks/rehype-pretty-code/assets/1284531/2ca0a0ee-0849-43d5-b184-1e468beaba5c)

Although this is a nextjs 13 app router project, but I don't use `@next/mdx`. It works fine if I replace the `rehype-pretty-code` by `rehype-highlight` or `rehype-prism-plus`.

![image](https://github.com/atomiks/rehype-pretty-code/assets/1284531/02ddabaa-5770-4042-a916-7156bab93ad7)

Thank you!

**Comment by baurine** [comment]
I resort to ChatGPT, it inspires me, and then I make it work. I am astonished by ChatGPT!

work code:

```
  const processedContent = await unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype)
    .use(rehypeSlug)
    .use(rehypeAutolinkHeadings)
    .use([[rehypePrettyCode, { theme: "one-dark-pro" }]])
    .use(rehypeStringify)
    .process(res.data.body ?? "")
```

Conversation with ChatGPT: https://chat.openai.com/share/39425667-83e4-41e8-9205-9e3ef476f4ee

**Comment by baurine** [comment]
but it's weird, the original code works in dev mode, just can't pass the build, don't know why.

btw, I think maybe we can add this usage to the doc, it's helpful for users like me.

**Comment by atomiks** [comment]
The types should be fixed in `0.9.7`

**Comment by baurine** [comment]
Cool~

The original code I mean the code before I modified to `use([[rehypePrettyCode, { theme: "one-dark-pro" }]])`. aka the following code:

```js
  const processedContent = await unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype)
    .use(rehypeSlug)
    .use(rehypeAutolinkHeadings)
    .use(rehypePrettyCode, { theme: "one-dark-pro" })
    .use(rehypeStringify)
    .process(res.data.body ?? "")
  const htmlContent = String(processedContent)
```

Although the VS Code reports the type error, and it fails when running `npm build` (aka `next build`), but it works with no error when I run `npm dev` (aka `next dev`).

**Comment by atomiks** [comment]
Yeah I think it was because the types were wrong, but runtime is fine, so it failed when typechecking but not when running. Hopefully 0.9.7 work fine?

**Comment by baurine** [comment]
Get it, look forward the new version!

**Comment by atomiks** [comment]
It's already published, you can test it out :D

**Comment by baurine** [comment]
> It's already published, you can test it out :D

wow, so fast, just go back from vacation, will test it today!

**Comment by baurine** [comment]
works great, thanks for your work!
