### ISSUE TITLE
Incorrect types

### ISSUE THREAD

**Issue by o-az** [atomiks/rehype-pretty-code#87]
```sh
Property 'children' does not exist on type 'Node<Data>'.ts
```

The `Node` type is the following (from `hast` which exports it from `uinst`):

```ts
export interface Node<TData extends object = Data> {
    type: string;
    data?: TData | undefined;
    position?: Position | undefined;
}
```

[In here](https://github.com/atomiks/rehype-pretty-code/blob/master/website/src/app/index.mdx#usage) the usage example has `node.children` and `node.properties` but neither children nor `properties` are properties of type `Node`.

**Comment by atomiks** [comment]
I think it should be `Element` not `Node` :(

**Comment by atomiks** [comment]
Yeah that would definitely be the best idea. Prior to 0.9.6 they just had `any` types, but adding the stricter types requires a lot more work/testing to make sure everything's good.

**Comment by atomiks** [comment]
I believe this is expected, as in this case you need to use a type guard to verify that the child is an `Element` node, and not something like a `Text` node. Something like this works:

```ts
import type {Element} from 'hast';

function isElement(value: any): value is Element {
  return value ? value.type === 'element' : false;
}
```
