### ISSUE TITLE
onig.wasm 404 (Not Found) when using React / Next.js "client component"

### ISSUE THREAD

**Issue by ben519** [atomiks/rehype-pretty-code#95]
I'm attempting to use rehype-pretty-code in a Next.js client component which looks something like this

```
import { unified } from "unified";
import rehypeStringify from "rehype-stringify";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import rehypePrettyCode from 'rehype-pretty-code';


export default async function processMD(text) {
  const processed = await unified()
    .use(remarkParse)
    .use(remarkRehype)
    .use(rehypePrettyCode)
    .use(rehypeStringify)
    .process(text);
  return processed;
}
```

This `processMD()` function is called from my client component to render some markdown in real time as the user edits a form. It works fine when `.use(rehypePrettyCode)` is excluded. With `.use(rehypePrettyCode)` included, I get the error

> GET http://localhost:3000/post/vZAFIG3WMOZngHeYSdjx/dist/onig.wasm 404 (Not Found)

[The docs](https://rehype-pretty-code.netlify.app/) have instructions on setting this up to be used with MDX, but I'm not using MDX. Any advice? If needed, I can put together a minimal reprex.

**Comment by atomiks** [comment]
This is a build-time/server-side highlighter, it doesn't work on the client

**Comment by atomiks** [comment]
Technically it might be able to work on the client, but not that straightforward:

https://github.com/atomiks/rehype-pretty-code/blob/024a5b8ec4a56318a6e6eac9221babce031fb851/test/chars-highlighter-playground/src/App.jsx#L42-L55

**Comment by nhtyy** [comment]
@atomiks thanks for the response,

so if i move my `unified().process` into some serverside code i can expect it work as intended?

will give it a shot thanks

**Comment by ben519** [comment]
Yes. Here's how I got it to work.

1. Copy the following files and folders

```
/node_modules/shiki/dist/onig.wasm -> public/dist/onig.wasm
/node_modules/shiki/languages/->         public/languages/
/node_modules/shiki/themes/->              public/themes/
```

2. Add the following lines of code

```
import { setCDN } from "shiki";

setCDN("/");
```

## Demo
![Screen Recording 2023-08-03 at 1 42 53 PM](https://github.com/atomiks/rehype-pretty-code/assets/723099/29aafba5-9424-4483-92e7-21403ec5b620)

**Comment by atomiks** [comment]
Very interesting @ben519, thanks! Guess that should be added to the docs.

**Comment by nhtyy** [comment]
@ben519 any chance you're deployed on vercel or netifly (& using next js?)

**Comment by ben519** [comment]
Vercel, but I haven't tested it yet. I'm still building things out locally at the moment.

**Comment by nhtyy** [comment]
@ben519 ah ok running into some issues documented them here https://github.com/atomiks/rehype-pretty-code/issues/98#issuecomment-1664860691

**Comment by atomiks** [comment]
Client side highlighting should work smoothly in `v0.12.0`.
