### ISSUE TITLE
Unable to control line numbering

### ISSUE THREAD

**Issue by Alex40144** [atomiks/rehype-pretty-code#99]
Hi,

my mdx file contains the following:
![image](https://github.com/atomiks/rehype-pretty-code/assets/10778669/45c85872-b6c3-4a64-8ff6-cd3230344c31)
the website shows:
![image](https://github.com/atomiks/rehype-pretty-code/assets/10778669/48030457-9d47-4e00-96c7-f3acef41b70b)
As you can see, I have no control over whether the line numbers show, I can't enable them, and they appear on the second instance of a code block (consistently across mdx files).

My code for generating this is
```
const mdSerialize = async (source: string) => {
    return await serialize(source, {
        mdxOptions: { rehypePlugins: [rehypePrettyCode] },
    });
};

const markdownWithMeta = fs.readFileSync(path.join('posts',
    id + '.mdx'), 'utf-8')

  const { data: frontMatter, content } = matter(markdownWithMeta)
  const mdxSource = await mdSerialize(content)
```
mdxSource is then passed into the MDXRemote html element. hopefully that makes sense.

I am using nextjs. please let me know what extra information you need, altenatively my repo is here: https://github.com/Alex40144/Personal-Website/tree/MDX

Thanks.

Alex.

**Comment by donnabrown77** [comment]
I download your code and was able to get line numbers to show by changing globals.css. I added:
code > [data-line]::before {
  counter-increment: line;
  content: counter(line);

  /* Other styling */
  display: inline-block;
  width: 1rem;
  margin-right: 2rem;
  text-align: right;
  color: gray;
}

**Comment by Alex40144** [comment]
Thanks @donnabrown77 , This turns line numbers on for everything, I was hoping I would be able to control it in the mdx file?

**Comment by rizkimcitra** [comment]
Same issue, the difference here with me is that `showLineNumbers` is enabled by default, and I can't disable them.
every code generated are having the `data-line` attribute to each lines of code

**Comment by atomiks** [comment]
`[data-line-numbers]` is a conditional attribute that only exists when you specify `showLineNumbers`, so you can scope the line numbers CSS to style only when that attribute is present on `code`

**Comment by rizkimcitra** [comment]
> 

thanks! I don't know I have that property, because I have my custom `<code>` in my MDX and I didn't pass all the props to it
so my mistake and it all works well now!
